<a href="https://colab.research.google.com/github/Om-shiv-verma/Machine-Learning/blob/main/Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python



Advantages of Numpy Arrays:

1.Allows several Mathematical Operations

2.Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [7]:
python_list = [i for i in range(100000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.009310423000000512


In [8]:
np_array = np.array([i for i in range(100000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.0002911259999995863


Numpy Arrays

In [10]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)


[1, 2, 3, 4, 5]


list

In [11]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [12]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
a.shape

(4,)

In [14]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
#2 rows, 4 col
b.shape

(2, 4)

In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [17]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [23]:
# create an identity matrix
a = np.eye(5)
print(a)
#all the diagonal value is one

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.57458816 0.54383731 0.20181549 0.60386982]
 [0.57842353 0.08181503 0.00335055 0.88294417]
 [0.86504093 0.84205737 0.02103483 0.83163202]]


In [27]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)
# range 10 to 100 and 3 rows ,5 cols

[[81 80 44 47 50]
 [58 31 95 72 80]
 [47 78 66 77 35]]


In [28]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


start : [optional] start of interval range. By default start = 0

stop  : end of interval range


step  : [optional] step size of interval. By default step size = 1,  
For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. 


dtype : type of output array

In [33]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,100,10)
print(e)

[10 20 30 40 50 60 70 80 90]


In [34]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [35]:
c = np.random.randint(10,90,(5,5))
print(c)

[[31 40 30 10 66]
 [57 26 81 21 50]
 [26 87 76 39 77]
 [22 64 20 88 48]
 [58 66 81 43 31]]


In [36]:
# array dimension
print(c.shape)

(5, 5)


In [37]:
# number of dimensions
print(c.ndim)

2


In [38]:
# number of elements in an array
print(c.size)

25


In [39]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [40]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [41]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [42]:
print(a)
print(b)

[[1 4 2]
 [9 1 4]
 [9 7 8]]
[[19 18 19]
 [19 13 11]
 [11 15 13]]


In [43]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 22 21]
 [28 14 15]
 [20 22 21]]
[[-18 -14 -17]
 [-10 -12  -7]
 [ -2  -8  -5]]
[[ 19  72  38]
 [171  13  44]
 [ 99 105 104]]
[[0.05263158 0.22222222 0.10526316]
 [0.47368421 0.07692308 0.36363636]
 [0.81818182 0.46666667 0.61538462]]


In [44]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [45]:
print(a)
print(b)

[[1 8 0]
 [9 2 9]
 [9 6 3]]
[[18 14 18]
 [19 12 19]
 [14 18 10]]


In [46]:

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 22 18]
 [28 14 28]
 [23 24 13]]
[[-17  -6 -18]
 [-10 -10 -10]
 [ -5 -12  -7]]
[[ 18 112   0]
 [171  24 171]
 [126 108  30]]
[[0.05555556 0.57142857 0.        ]
 [0.47368421 0.16666667 0.47368421]
 [0.64285714 0.33333333 0.3       ]]


Array Manipulation

In [47]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 0 2]
 [6 7 8]]
(2, 3)


In [48]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 6]
 [0 7]
 [2 8]]
(3, 2)


In [50]:
array1 = np.random.randint(0,10,(2,3))
print(array1)
print(array1.shape)

[[8 1 5]
 [0 8 8]]
(2, 3)


In [51]:
trans2 = array1.T
print(trans2)
print(trans2.shape)

[[8 0]
 [1 8]
 [5 8]]
(3, 2)


In [52]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[4 2 3]
 [3 8 3]]
(2, 3)


In [53]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 2]
 [3 3]
 [8 3]]
(3, 2)
